# Generated by Django 5.2.1 on 2025-06-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0002_alter_analysisresult_signal_alter_ecgsignal_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgsignal',
            name='sampling_rate',
            field=models.PositiveIntegerField(default=100, help_text='If provided on upload, overrides the default 100 Hz.', verbose_name='Sampling rate (Hz)'),
        ),
    ]
