# Generated by Django 5.2.1 on 2025-05-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_csvresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvresult',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='csvresult',
            name='csv_file',
            field=models.FileField(upload_to='csv_results/', verbose_name='Plik CSV'),
        ),
        migrations.AlterField(
            model_name='csvresult',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='csvresult',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania'),
        ),
    ]
