# Generated by Django 5.2.1 on 2025-06-08 12:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='csvresult',
            name='exam_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Data wykonania badania'),
        ),
        migrations.AddField(
            model_name='csvresult',
            name='pesel',
            field=models.CharField(default='', max_length=11, verbose_name='Numer PESEL'),
        ),
        migrations.AddField(
            model_name='csvresult',
            name='sampling_rate',
            field=models.PositiveIntegerField(default=100, verbose_name='Częstotliwość próbki (Hz)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
