# Generated by Django 5.2.1 on 2025-06-09 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_csvresult_exam_date_csvresult_pesel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctor',
        ),
        migrations.AddField(
            model_name='profile',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
